using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using PoleBarnGenerator.Models;
using PoleBarnGenerator.Models.Analysis;
using PoleBarnGenerator.Models.Design;
using PoleBarnGenerator.Models.Code;

namespace PoleBarnGenerator.Generators
{
    /// <summary>
    /// Generates professional structural calculation packages for engineer review and PE stamping.
    /// Note: report values include preliminary/simplified analysis outputs and are not construction-ready by themselves.
    /// </summary>
    public static class EngineeringReportGenerator
    {
        /// <summary>
        /// Generate a complete structural calculation report as formatted text.
        /// Suitable for inclusion in a professional calculation package.
        /// </summary>
        public static string GenerateCalculationReport(BarnGeometry geometry,
            StructuralDesignResult design, string projectName = "", string engineerName = "")
        {
            var sb = new StringBuilder();
            var p = geometry.Params;

            // Title block
            sb.AppendLine("╔══════════════════════════════════════════════════════════╗");
            sb.AppendLine("║         STRUCTURAL CALCULATION PACKAGE                  ║");
            sb.AppendLine("║         Generated by FrameSmith                         ║");
            sb.AppendLine("╚══════════════════════════════════════════════════════════╝");
            sb.AppendLine(GetPreliminaryDisclaimer());
            sb.AppendLine();
            if (!string.IsNullOrEmpty(projectName))
                sb.AppendLine($"  Project: {projectName}");
            sb.AppendLine($"  Date: {DateTime.Now:yyyy-MM-dd}");
            sb.AppendLine($"  Building: {p.BuildingWidth}' × {p.BuildingLength}' × {p.EaveHeight}' Eave");
            sb.AppendLine($"  Roof Pitch: {p.RoofPitchRise}/12 ({p.TrussType} Truss)");
            sb.AppendLine($"  Peak Height: {geometry.PeakHeight:F1}'");
            sb.AppendLine($"  Bay Spacing: {p.ActualBaySpacing:F1}' ({geometry.NumBays} bays)");
            sb.AppendLine();

            // Engineer seal block
            sb.AppendLine("┌──────────────────────────────────────┐");
            sb.AppendLine("│  ENGINEER SEAL / SIGNATURE           │");
            sb.AppendLine("│                                      │");
            if (!string.IsNullOrEmpty(engineerName))
                sb.AppendLine($"│  {engineerName,-36} │");
            else
                sb.AppendLine("│  ________________________________    │");
            sb.AppendLine("│  PE License No: ________________    │");
            sb.AppendLine("│  Date: _________________________    │");
            sb.AppendLine("└──────────────────────────────────────┘");
            sb.AppendLine();

            // Design criteria
            sb.AppendLine("═══ 1. DESIGN CRITERIA ═══");
            sb.AppendLine();
            sb.AppendLine("  Applicable Codes:");
            foreach (var code in design.CodeCompliance.ApplicableCodes)
                sb.AppendLine($"    • {code.Code} {code.Section} — {code.Description}");
            sb.AppendLine();

            // Load parameters
            sb.AppendLine("═══ 2. DESIGN LOADS ═══");
            sb.AppendLine();
            sb.AppendLine("  2.1 Wind Loads (ASCE 7-22)");
            sb.AppendLine($"    Basic Wind Speed: V = {design.WindLoads.BasicWindSpeed:F0} mph");
            sb.AppendLine($"    Velocity Pressure: qh = {design.WindLoads.VelocityPressure:F1} psf");
            sb.AppendLine($"    Windward Wall:    p = {design.WindLoads.WindwardWallPressure:F1} psf");
            sb.AppendLine($"    Leeward Wall:     p = {design.WindLoads.LeewardWallPressure:F1} psf");
            sb.AppendLine($"    Side Walls:       p = {design.WindLoads.SideWallPressure:F1} psf");
            sb.AppendLine($"    Roof Windward:    p = {design.WindLoads.RoofWindwardPressure:F1} psf");
            sb.AppendLine($"    Roof Leeward:     p = {design.WindLoads.RoofLeewardPressure:F1} psf");
            sb.AppendLine($"    Max Uplift:       p = {design.WindLoads.UpliftPressure:F1} psf");
            sb.AppendLine($"    C&C (Zone 3):     p = {design.WindLoads.ComponentCladdingPressure:F1} psf");
            sb.AppendLine();
            foreach (var r in design.WindLoads.CodeReferences)
                sb.AppendLine($"    Ref: {r}");
            sb.AppendLine();

            sb.AppendLine("  2.2 Snow Loads (ASCE 7-22)");
            sb.AppendLine($"    Ground Snow:      pg = {design.SnowLoads.GroundSnowLoad:F1} psf");
            sb.AppendLine($"    Flat Roof:        pf = {design.SnowLoads.FlatRoofSnowLoad:F1} psf");
            sb.AppendLine($"    Sloped Roof:      ps = {design.SnowLoads.SlopedRoofSnowLoad:F1} psf");
            sb.AppendLine($"    Unbalanced:       pu = {design.SnowLoads.UnbalancedSnowLoad:F1} psf");
            sb.AppendLine($"    Design Roof Snow: S  = {design.SnowLoads.DesignRoofSnowLoad:F1} psf");
            sb.AppendLine($"    Ce={design.SnowLoads.ExposureFactor}, Ct={design.SnowLoads.ThermalFactor}, Cs={design.SnowLoads.SlopeReductionFactor:F3}");
            sb.AppendLine();

            sb.AppendLine("  2.3 Live Loads (IBC 2021)");
            sb.AppendLine($"    Floor Live:       L  = {design.LiveLoads.ReducedFloorLiveLoad:F1} psf");
            sb.AppendLine($"    Roof Live:        Lr = {design.LiveLoads.ReducedRoofLiveLoad:F1} psf");
            sb.AppendLine();

            sb.AppendLine("  2.4 Dead Loads");
            sb.AppendLine($"    Roof (horiz proj): D = {design.DeadLoads.TotalRoofDead:F1} psf");
            sb.AppendLine($"    Wall:              D = {design.DeadLoads.TotalWallDead:F1} psf");
            foreach (var kv in design.DeadLoads.Breakdown)
                sb.AppendLine($"      {kv.Key}: {kv.Value:F1} psf");
            sb.AppendLine();

            // Member wind loads
            sb.AppendLine("  2.5 Member Wind Loads");
            sb.AppendLine($"    {"Member",-28} {"Trib (sf)",-12} {"Pressure",-12} {"Linear (plf)"}");
            sb.AppendLine($"    {"─────────────────────────────",-28} {"─────────",-12} {"─────────",-12} {"──────────"}");
            foreach (var ml in design.WindLoads.MemberLoads)
                sb.AppendLine($"    {ml.MemberType,-28} {ml.TributaryArea,-12:F1} {ml.DesignPressure,-12:F1} {ml.LinearLoad:F1}");
            sb.AppendLine();

            // Structural analysis
            sb.AppendLine("═══ 3. STRUCTURAL ANALYSIS ═══");
            sb.AppendLine();
            sb.AppendLine($"  Controlling Combo: {design.Analysis.ControllingLoadCombo}");
            sb.AppendLine();
            sb.AppendLine("  3.1 Post Forces");
            foreach (var pf in design.Analysis.PostForces)
            {
                sb.AppendLine($"    {pf.MemberType} ({pf.Location}):");
                sb.AppendLine($"      Axial: {pf.AxialForce:F0} lbs, Shear: {pf.ShearForce:F0} lbs, Moment: {pf.BendingMoment:F0} ft-lbs");
                sb.AppendLine($"      Controlling: {pf.ControllingCombo}");
            }
            sb.AppendLine();

            sb.AppendLine("  3.2 Girt Forces");
            foreach (var gf in design.Analysis.GirtForces)
                sb.AppendLine($"    {gf.MemberType}: M={gf.BendingMoment:F0} ft-lbs, V={gf.ShearForce:F0} lbs ({gf.ControllingCombo})");
            sb.AppendLine();

            sb.AppendLine("  3.3 Purlin Forces");
            foreach (var prf in design.Analysis.PurlinForces)
                sb.AppendLine($"    {prf.MemberType}: M={prf.BendingMoment:F0} ft-lbs, V={prf.ShearForce:F0} lbs ({prf.ControllingCombo})");
            sb.AppendLine();

            sb.AppendLine("  3.4 Foundation Reactions");
            foreach (var fr in design.Analysis.FoundationReactions)
            {
                sb.AppendLine($"    {fr.Location}:");
                sb.AppendLine($"      Vertical: {fr.VerticalReaction:F0} lbs, Horizontal: {fr.HorizontalReaction:F0} lbs");
                if (fr.UpliftForce > 0)
                    sb.AppendLine($"      NET UPLIFT: {fr.UpliftForce:F0} lbs");
            }
            sb.AppendLine();

            // Member design
            sb.AppendLine("═══ 4. MEMBER DESIGN ═══");
            sb.AppendLine();
            sb.AppendLine("  4.1 Post Design (NDS 2024 §3.7, §3.9)");
            sb.AppendLine($"    Size: {design.PostDesign.RequiredSize?.Name ?? "N/A"}");
            sb.AppendLine($"    Combined Ratio: {design.PostDesign.CombinedRatio:F3} ≤ 1.0 {(design.PostDesign.IsAdequate ? "✓ OK" : "✗ NG")}");
            sb.AppendLine($"    Slenderness: le/d = {design.PostDesign.SlendernessRatio:F1} ≤ 50 {(design.PostDesign.SlendernessRatio <= 50 ? "✓" : "✗")}");
            sb.AppendLine($"    Compression Capacity: {design.PostDesign.CompressionCapacity:F0} lbs");
            sb.AppendLine($"    Buckling Capacity: {design.PostDesign.BucklingCapacity:F0} lbs");
            foreach (var r in design.PostDesign.CodeReferences)
                sb.AppendLine($"    {r}");
            sb.AppendLine();

            sb.AppendLine("  4.2 Girt Design (NDS 2024 §3.3, §3.4)");
            sb.AppendLine($"    Size: {design.GirtDesign.RequiredSize?.Name ?? "N/A"}");
            sb.AppendLine($"    Bending Ratio: {design.GirtDesign.MomentCapacityRatio:F3} ≤ 1.0 {(design.GirtDesign.MomentCapacityRatio <= 1 ? "✓" : "✗")}");
            sb.AppendLine($"    Shear Ratio: {design.GirtDesign.ShearCapacityRatio:F3} ≤ 1.0 {(design.GirtDesign.ShearCapacityRatio <= 1 ? "✓" : "✗")}");
            sb.AppendLine($"    Deflection: {design.GirtDesign.ActualDeflection:F3}\" ≤ {design.GirtDesign.AllowableDeflection:F3}\" {(design.GirtDesign.MeetsDeflectionLimit ? "✓" : "✗")}");
            sb.AppendLine();

            sb.AppendLine("  4.3 Purlin Design (NDS 2024 §3.3, §3.4)");
            sb.AppendLine($"    Size: {design.PurlinDesign.RequiredSize?.Name ?? "N/A"}");
            sb.AppendLine($"    Bending Ratio: {design.PurlinDesign.MomentCapacityRatio:F3} ≤ 1.0 {(design.PurlinDesign.MomentCapacityRatio <= 1 ? "✓" : "✗")}");
            sb.AppendLine($"    Shear Ratio: {design.PurlinDesign.ShearCapacityRatio:F3} ≤ 1.0 {(design.PurlinDesign.ShearCapacityRatio <= 1 ? "✓" : "✗")}");
            sb.AppendLine($"    Deflection: {design.PurlinDesign.ActualDeflection:F3}\" ≤ {design.PurlinDesign.AllowableDeflection:F3}\" {(design.PurlinDesign.MeetsDeflectionLimit ? "✓" : "✗")}");
            sb.AppendLine();

            // Foundation
            sb.AppendLine("═══ 5. FOUNDATION DESIGN ═══");
            sb.AppendLine();
            sb.AppendLine($"  Footing Diameter: {design.FoundationDesign.FootingDiameter}\"");
            sb.AppendLine($"  Footing Pad Depth: {design.FoundationDesign.FootingDepth}\"");
            sb.AppendLine($"  Post Embedment: {design.FoundationDesign.PostEmbedment}\"");
            sb.AppendLine($"  Total Hole Depth: {design.FoundationDesign.TotalHoleDepth}\"");
            sb.AppendLine($"  Concrete: f'c = {design.FoundationDesign.ConcreteStrength} psi");
            sb.AppendLine($"  Concrete Volume: {design.FoundationDesign.ConcreteVolume:F2} cf per footing");
            sb.AppendLine($"  Reinforcement Required: {(design.FoundationDesign.RequiresReinforcement ? "Yes" : "No")}");
            sb.AppendLine($"  Bearing Ratio: {design.FoundationDesign.BearingRatio:F3} ≤ 1.0 {(design.FoundationDesign.BearingRatio <= 1 ? "✓" : "✗")}");
            sb.AppendLine($"  Overturning SF: {design.FoundationDesign.OverturningSafetyFactor:F2} ≥ 1.5 {(design.FoundationDesign.OverturningSafetyFactor >= 1.5 ? "✓" : "✗")}");
            sb.AppendLine($"  Sliding SF: {design.FoundationDesign.SlidingSafetyFactor:F2} ≥ 1.5 {(design.FoundationDesign.SlidingSafetyFactor >= 1.5 ? "✓" : "✗")}");
            if (design.FoundationDesign.UpliftSafetyFactor < 90)
                sb.AppendLine($"  Uplift SF: {design.FoundationDesign.UpliftSafetyFactor:F2} ≥ 1.5 {(design.FoundationDesign.UpliftSafetyFactor >= 1.5 ? "✓" : "✗")}");
            sb.AppendLine($"  Drainage: {design.FoundationDesign.Drainage}");
            sb.AppendLine();

            // Code compliance
            sb.AppendLine("═══ 6. CODE COMPLIANCE ═══");
            sb.AppendLine();
            sb.AppendLine($"  Status: {design.CodeCompliance.Summary}");
            sb.AppendLine();
            foreach (var issue in design.CodeCompliance.Issues)
            {
                string icon = issue.Severity == IssueSeverity.Error ? "✗" :
                              issue.Severity == IssueSeverity.Warning ? "⚠" : "ℹ";
                sb.AppendLine($"  {icon} [{issue.Severity}] {issue.Description}");
                sb.AppendLine($"    Code: {issue.CodeSection}");
                if (!string.IsNullOrEmpty(issue.Resolution))
                    sb.AppendLine($"    Resolution: {issue.Resolution}");
                if (issue.RequiresEngineerReview)
                    sb.AppendLine($"    ** REQUIRES ENGINEER REVIEW **");
                sb.AppendLine();
            }

            // Member schedule
            sb.AppendLine("═══ 7. MEMBER SCHEDULE ═══");
            sb.AppendLine();
            sb.AppendLine($"  {"Member",-16} {"Size",-14} {"Grade",-16} {"Spacing",-14} {"Ratio",-8} {"Status"}");
            sb.AppendLine($"  {"────────────────",-16} {"──────────────",-14} {"────────────────",-16} {"──────────────",-14} {"──────",-8} {"──────"}");
            foreach (var m in design.MemberSchedule)
                sb.AppendLine($"  {m.Type,-16} {m.Size,-14} {m.Grade,-16} {m.Spacing,-14} {m.Ratio,-8:F3} {m.Status}");
            sb.AppendLine();

            // Assumptions & notes
            sb.AppendLine("═══ 8. ASSUMPTIONS & NOTES ═══");
            sb.AppendLine();
            sb.AppendLine("  1. Building is classified as enclosed per ASCE 7-22 §26.2");
            sb.AppendLine("  2. Post-frame (pole barn) construction per ASAE EP486");
            sb.AppendLine("  3. Posts embedded in concrete with gravel drainage pad");
            sb.AppendLine("  4. Trusses by truss manufacturer — verify with shop drawings");
            sb.AppendLine("  5. All lumber assumed dry, treated where in ground contact");
            sb.AppendLine("  6. Soil bearing capacity assumed — verify with geotechnical report");
            sb.AppendLine("  7. Connections not detailed — verify per NDS Chapter 12");
            sb.AppendLine("  8. Diaphragm action of metal roof/wall panels assumed");
            sb.AppendLine();

            if (design.Analysis.Warnings.Count > 0)
            {
                sb.AppendLine("  *** WARNINGS ***");
                foreach (var w in design.Analysis.Warnings)
                    sb.AppendLine($"  ⚠ {w}");
                sb.AppendLine();
            }

            sb.AppendLine("═══ END OF CALCULATIONS ═══");

            return sb.ToString();
        }

        /// <summary>
        /// Generate load table data for placement on drawings.
        /// Returns structured data that drawing generators can use.
        /// </summary>
        public static List<string[]> GenerateLoadTableRows(StructuralDesignResult design)
        {
            var rows = new List<string[]>
            {
                new[] { "LOAD TYPE", "VALUE", "CODE REF" },
                new[] { "Ground Snow (pg)", $"{design.SnowLoads.GroundSnowLoad:F0} psf", "ASCE 7-22 Fig 7.2-1" },
                new[] { "Roof Snow (ps)", $"{design.SnowLoads.DesignRoofSnowLoad:F0} psf", "ASCE 7-22 §7.4" },
                new[] { "Wind Speed (V)", $"{design.WindLoads.BasicWindSpeed:F0} mph", "ASCE 7-22 §26.5" },
                new[] { "Velocity Pressure (qh)", $"{design.WindLoads.VelocityPressure:F1} psf", "ASCE 7-22 §26.10" },
                new[] { "Roof Dead (D)", $"{design.DeadLoads.TotalRoofDead:F1} psf", "ASCE 7-22 Ch.3" },
                new[] { "Roof Live (Lr)", $"{design.LiveLoads.ReducedRoofLiveLoad:F0} psf", "ASCE 7-22 §4.8" },
                new[] { "Floor Live (L)", $"{design.LiveLoads.ReducedFloorLiveLoad:F0} psf", "IBC Table 1607.1" },
            };
            return rows;
        }

        /// <summary>
        /// Standard report disclaimer for early-stage structural outputs.
        /// </summary>
        public static string GetPreliminaryDisclaimer()
        {
            return "  PRELIMINARY - NOT FOR CONSTRUCTION";
        }

        /// <summary>
        /// Generate member schedule rows for placement on drawings.
        /// </summary>
        public static List<string[]> GenerateMemberScheduleRows(StructuralDesignResult design)
        {
            var rows = new List<string[]> { new[] { "MEMBER", "SIZE", "GRADE", "SPACING" } };
            foreach (var m in design.MemberSchedule)
                rows.Add(new[] { m.Type, m.Size, m.Grade, m.Spacing });
            return rows;
        }

        /// <summary>
        /// Generate foundation schedule rows for placement on drawings.
        /// </summary>
        public static List<string[]> GenerateFoundationScheduleRows(StructuralDesignResult design)
        {
            var f = design.FoundationDesign;
            return new List<string[]>
            {
                new[] { "FOUNDATION SCHEDULE", "", "" },
                new[] { "Footing Diameter", $"{f.FootingDiameter}\"", "" },
                new[] { "Footing Pad Depth", $"{f.FootingDepth}\"", "" },
                new[] { "Post Embedment", $"{f.PostEmbedment}\"", "" },
                new[] { "Total Hole Depth", $"{f.TotalHoleDepth}\"", "" },
                new[] { "Concrete Strength", $"f'c = {f.ConcreteStrength} psi", "" },
                new[] { "Drainage", $"{f.Drainage}", "" },
            };
        }
    }
}
